"""add failed reconciliations

Revision ID: cba62fd2f98b
Revises: 2c954ccd3ef3
Create Date: 2026-07-06 23:42:19.002429
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cba62fd2f98b'
down_revision: str | None = '2c954ccd3ef3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_reconciliations',
    sa.Column('provider_name', sa.String(length=30), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', sa.String(length=4000), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_virtual_accounts_nomba_account_ref'), table_name='virtual_accounts')
    op.create_unique_constraint(None, 'virtual_accounts', ['nomba_account_ref'])
    op.drop_index(op.f('ix_wallet_transactions_reference'), table_name='wallet_transactions')
    op.create_unique_constraint(None, 'wallet_transactions', ['reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_transactions', type_='unique')
    op.create_index(op.f('ix_wallet_transactions_reference'), 'wallet_transactions', ['reference'], unique=True)
    op.drop_constraint(None, 'virtual_accounts', type_='unique')
    op.create_index(op.f('ix_virtual_accounts_nomba_account_ref'), 'virtual_accounts', ['nomba_account_ref'], unique=True)
    op.drop_table('failed_reconciliations')
    # ### end Alembic commands ###
